[project]
name = "repl-nix-carsales"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.36",
]
